name: Run Poster Generate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  # please change to your own config.
  # this actions generate only this year
  # If you fork this please change the type to yours below
  TYPE: "strava, github, forest, pass" # support strava/gpx/ns/cichang/shanbay/duolingo/issue/leetcode/twitter/github/gitlab/kindle/bilibili/wakatime/dota2/forest, Please change the 'pass' it to your own separated by commas
  ME: yihong0618

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # from https://github.com/pdm-project/pdm/blob/main/.github/workflows/ci.yml
      - name: Set Variables
        id: set_variables
        shell: bash
        run: |
          echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_OUTPUT
          echo "PIP_CACHE=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Cache PIP
        uses: actions/cache@v3
        with:
          path: ${{ steps.set_variables.outputs.PIP_CACHE }}
          key: ${{ runner.os }}-pip-${{ steps.set_variables.outputs.PY }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Run sync issue script
        if: contains(env.TYPE, 'issue')
        run: |
          github_poster issue --issue_number ${{ vars.ISSUE_NUMBER_01 }} --repo_name ${{ vars.REPO_NAME }} --github_token ${{ secrets.GITHUB_TOKEN }} --me ${{ vars.ISSUE_NUMBER_01_ME }}
          mv issue.svg issue_${{ vars.ISSUE_NUMBER_01 }}.svg

      - name: Push new postger
        run: |
          git config --local user.email ${{ vars.COMMIT_USER_EMAIL }}
          git config --local user.name ${{ vars.COMMIT_USER_NAME }}
          git add .
          git commit -m 'update new poster' || echo "nothing to commit"
          git push || echo "nothing to push"
